### ISSUE TITLE
Apa Isinya?

### ISSUE THREAD

**Issue by mzaini30** [LibreOffice-Indonesia/android-user#1]
Maaf saya mau tanya, repository ini nanti mau diisi apa ya?
Terima kasih

**Comment by rhonyabdullah** [comment]
Repo ini nanti akan di isi apps mengenai penggunaan libreOffice writer yang contentnya di ambil dari buku libreOffice dan sedang dalam tahap pengembangan silahkan cek di sini [url buku](https://ubupediaindonesia.wordpress.com/category/ebook-linux/) 

Silahkan join ke group slack kami lewat inbox dari telegram untuk diskusi lebih detail mengenai apps yang akan di bangun.
