### ISSUE TITLE
Perkembangan Development

### ISSUE THREAD

**Issue by suciptoid** [LibreOffice-Indonesia/android-user#2]
Tim dev, bagaimana perkembangan / kelanjutan proyek ini?

**Comment by rhonyabdullah** [comment]
mas @showcheap thanks sudah menanyakan, maaf, kami terkendala dengan resource developernya mas, untuk design app ini kita sebenarnya sudah complete sekitar 65%, silahkan cek disini [Trello Board - Lebih Dekat Dengan LibreOffice](https://trello.com/b/15bcZxwn). Kalau mas Cipto tertarik dalam pengembangan saya bisa bantu untuk arahin.
